name: Rails CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      MYSQL_ROOT_PASSWORD: password
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      TEST_DATABASE_USER: root
      TEST_DATABASE_PASSWORD: password

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: lift_quest_api_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.0'
        bundler-cache: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libmysqlclient-dev
        bundle install

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"3306" -u"root" -p"password" --silent; do
          sleep 1
        done

    - name: Set up database
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load

    - name: Run tests
      run: bundle exec rails test

    - name: Debug Environment
      run: |
        echo "Current environment variables:"
        env
        echo "MySQL connection test:"
        mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e "SHOW DATABASES;"